### ISSUE TITLE
rename error

### ISSUE THREAD

**Issue by barnett2010** [vinhtq115/rename-torrent-from-hash#3]
When there are many files,   1000
I can't change  name
There will be mistakes

`
  python rename-from-hash.py
Enter torrent folder path:torrentcache
Traceback (most recent call last):
  File "rename-from-hash.py", line 13, in <module>
    torrent = Torrent.from_file(filepath)
  File "C:\Python38\lib\site-packages\torrentool\torrent.py", line 434, in from_
file
    torrent = cls(Bencode.read_file(filepath))
  File "C:\Python38\lib\site-packages\torrentool\bencode.py", line 204, in read_
file
    return cls.decode(contents)
  File "C:\Python38\lib\site-packages\torrentool\bencode.py", line 172, in decod
e
    raise BencodeDecodingError('Unable to interpret `%s` char.' % char)
torrentool.exceptions.BencodeDecodingError: Unable to interpret `:` char.
`

**Comment by barnett2010** [comment]
bt file https://mega.nz/file/PCABkYBZ#uuF7_eQYDjqCyjrq8T2LRoOKUohuVdW-GNcpe89TIb4
